### ISSUE TITLE
about pre-trained models

### ISSUE THREAD

**Issue by anshaopei** [makinyilmaz/LHBDC#1]
Thanks for your excellent work! We intend to reproduce your results,but we can not find your pre-trained models. So where can we find your pre-trained models?

**Comment by makinyilmaz** [comment]
Thanks for your interest and reminder. I will put the pre-trained models in a very short time

**Comment by m-guise** [comment]
@makinyilmaz Can you share the pre-trained model? Also, if possible, share the training script as well.

**Comment by makinyilmaz** [comment]
I shared pretrained weights for different ratios via a drive link. I willl also share the training code soon

**Comment by aboyandaworld** [comment]
Thank you for your outstanding contribution! We are very interested in your code. I am planning to reproduce your work and would like to request your training code to better understand and learn from it. I have read through your project documentation and relevant papers, and have made an effort to understand the details of the code.
